# Generated by Django 3.2.22 on 2023-11-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20231031_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='gsttype',
        ),
        migrations.AddField(
            model_name='invoice',
            name='adjust',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_no',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cheque_no',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paidoff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pay_method',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tot_inv_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='upi_no',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recinvoice',
            name='adjust',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recinvoice',
            name='balance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recinvoice',
            name='bank_no',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recinvoice',
            name='cheque_no',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recinvoice',
            name='entity_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recinvoice',
            name='paidoff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recinvoice',
            name='pay_method',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recinvoice',
            name='shipping_charge',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recinvoice',
            name='tot_inv_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recinvoice',
            name='upi_no',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='duedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recinvoice',
            name='subtotal',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recinvoice',
            name='taxamount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recinvoice_item',
            name='product',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
