# Generated by Django 3.2.22 on 2023-11-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_auto_20231104_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='placesupply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='acc_no',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='adjustment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='balance',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='bank_id',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='cgst',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='cheque_no',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='file',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='crdit_note/'),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='igst',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='payment_method',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='reference_number',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='sgst',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='upi_id',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salescreditnote',
            name='credit_no',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
