# Generated by Django 3.2.22 on 2023-11-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_auto_20231108_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='bank_names',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
