# Generated by Django 3.2.22 on 2023-11-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_salescreditnote1_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_loan_tran',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee_loan_tran',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee_loan_tran',
            name='upi_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='upi_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
