# Generated by Django 3.2.22 on 2023-11-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_bank_transactions_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='prfile',
            field=models.IntegerField(default=0),
        ),
    ]
