# Generated by Django 3.2.22 on 2023-11-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_company_prfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='reference',
            field=models.IntegerField(default=0),
        ),
    ]
