# Generated by Django 3.2.22 on 2023-11-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_alter_purchasebill_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_loan_tran',
            name='balance_loan',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='recurring_bill',
            name='billno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
