# Generated by Django 3.2.22 on 2023-11-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_alter_employee_loan_tran_balance_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_loan_tran',
            name='balance_loan',
        ),
    ]
