# Generated by Django 3.2.22 on 2023-11-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_paymentitems_invid'),
    ]

    operations = [
        migrations.AddField(
            model_name='retainerinvoices',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
