# Generated by Django 3.2.22 on 2023-12-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_retainerinvoices_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_account',
            name='desc',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan_account',
            name='intrest',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan_account',
            name='paid',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan_account',
            name='processing',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan_transaction',
            name='loan_intrest',
            field=models.TextField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
